# Sorular ve cevaplar
sorular = [
"Güneş, Dünya ve Ay'ın dönüş yönlerini açıkla.",
"Güneş'in dönüş yönünü açıkla.",
"Dünya'nın dönüş yönünü açıkla.",
"Ay'ın dönüş yönünü açıkla.",
"Güneş, Dünya ve Ay'ın hareketlerini modelleme.",
"Güneş'in yapısını açıkla." ,
"Güneş'in katmanlarını açıkla.",
"Güneş'in özelliklerini listele.",
"Güneş olmasaydı neler olurdu?",
"Güneş'i nasıl gözlemleriz?",
"Güneş modeli nasıl oluşturulur?",
"Güneş'in katmanları nelerdir?" ,
"Ay'ın hareketlerini açıkla.",
"Ay neden değişik şekillerde görünür?",
"Ay'ın evrelerini açıkla.",
"Ay'ın evrelerini listele.",
"Kütle ve ağırlık arasındaki farkları açıkla.",
"Ağırlığın özelliklerini açıkla.",
"Kütle çekim kuvvetini açıkla.",
"Sürtünme kuvvetini açıkla.",
"Sürtünme kuvvetinin özelliklerini açıkla.",
"Pürüzlü ve kaygan yüzeyleri açıkla.",
"Sürtünme kuvvetini azaltmanın yollarını açıkla.",
"Sürtünme kuvvetinin etkilerini açıkla.",
"Havadaki sürtünme kuvvetini açıkla.",
"Sudaki sürtünme kuvvetini açıkla.",
"Su direncini azaltmanın yollarını açıkla.",
"Kuvveti açıkla.",
"Kuvvetin cisimler üzerine etkilerini açıkla.",
"Kuvvetle neler yapılabilir?",
"Dinamometre açıklamasını yap.",
"Esnek cisimleri açıkla.",
"Dinamometre nasıl yapılır?",
"5. Sınıf Destek ve Hareket Sistemi konusunu açıklayın.",
"Destek ve Hareket Sistemi'nin bileşenlerini açıklayın.",
"Kemikler hakkında bilgi verin.",
"İskeletin görevlerini listeleyin.",
"Kemik türlerini açıklayın.",
"En uzun ve en kısa kemikleri belirtin.",
"Röntgenin kullanım alanlarını açıklayın.",
"Eklem türlerini açıklayın.",
"Kıkırdak hakkında bilgi verin.",
"Kas türlerini açıklayın.",
"Mikroskopun tanımını ve kullanımını açıklayın.",
"Mikroskobun kullanım adımlarını listeleyin.",
"Hücre bilgisinin tarihsel gelişimini açıklayın.",
"Hücreyi tanımlayın.",
"Hücrenin temel kısımlarını açıklayın.",
"Hücre zarının özelliklerini açıklayın.",
"Hücre duvarının özelliklerini açıklayın.",
"Sitoplazmanın özelliklerini açıklayın.",
"Hücrede bulunan organelleri listeleyin ve açıklayın.",
"Çekirdeği açıklayın.",
"Bitki ve hayvan hücresi arasındaki farklılıkları listeleyin.",
"Hücreden organizmaya olan sıralanışı açıklayın.",
"Işığın madde ile etkileşimini açıklayın.",
"Opak madde nedir?",
"Yarı saydam madde nedir?",
"Saydam madde nedir?",
"Maddelerin saydamlık özelliği değişebilir mi?",
"Tam gölge nedir?",
"Gölge nasıl çizilir?",
"Gölgenin büyüklüğü nasıl değişir?",
"Yarı gölge nedir?",
"Gölge oluşumu hangi alanlarda kullanılır?",
"Işık nasıl yayılır?",
"Işığın doğrusal yolla yayıldığı nasıl anlaşılır?",
"Işık kaynakları nedir?",
"1. Güneş (En büyük doğal ışık kaynağımızdır)",
"Yapay ışık kaynaklarına örnekler verin.",
"5. sınıf maddenin tanecikli yapısını açıkla.",
"Maddenin hallerini açıkla.",
"Isı ve sıcaklık kavramlarını açıkla.",
"Isı ve sıcaklığın farklarını açıkla.",
"Maddenin hal değişimlerini açıkla.",
"Binalarda isı yalıtımının önemini açıkla.",
"Isı iletkeni ve ısı yalıtkanlarına örnekler ver.",
"Isı yalıtım malzemelerinin olması gereken özelliklerini açıkla.",
"Binalarda kullanılan isı yalıtım malzemelerini açıkla.",
"Basit bir elektrik devresi hakkında bilgi ver.",
"Basit elektrik devresinde kullanılan devre elemanlarının görevlerini açıkla.",
"Basit elektrik devresinde ampul neden ışık vermez?",
"Bilimsel araştırma yöntemi nedir?",
"Değişken nedir?",
"Elektrik devresinde pil sayısının artırılması ampulün parlaklığını nasıl değiştirir?",
"Elektrik devresinde ampul sayısının artırılması ampulün parlaklığını nasıl değiştirir?",
"Elektrik düğmeleri (devre anahtarı) hakkında bilgi ver.",
"Devre elemanlarının sembollerle gösterilmesinin sebeplerini açıkla.",
"Devre elemanlarının görevlerini açıkla.",
"Yardımcı devre elemanları hakkında bilgi ver.",
"Devre şeması hakkında bilgi ver.",
"Atık ve çöp arasındaki farkı açıkla.",
"Yeniden kullanma ve geri dönüşüm arasındaki farkı açıkla.",
"Kompost nedir?",
"Geri kazanım nedir?",
"Evsel atık nedir?",
 "Evsel katı atık nedir?",
"Evsel sıvı atık nedir?",
"Organik atık nedir?",
 "Tıbbi atık nedir?",
"Geri dönüşümün aşamaları nelerdir?",
"Geri dönüştürülebilen evsel atıklar nelerdir?",
"Geri dönüşümü olmayan evsel atıklar nelerdir?",
"Geri dönüşümün sağladığı yararlar nelerdir?",
"Atık yönetimi nedir?",
"Atık kontrolü ile ilgili kuruluşlar nelerdir?",
]

cevaplar = [
"Güneş, Dünya ve Ay kendi ekseni etrafında saat yönünün tersinde dönmektedir. Dünya, Güneş etrafında saat yönünün tersinde dolanmaktadır. Ay, Dünya ve Güneş etrafında saat yönünün tersinde dolanmaktadır.",
"Güneş kendi ekseni etrafında saat yönünün tersinde dönmektedir.",
"Dünya kendi ekseni etrafında saat yönünün tersinde dönmektedir. Dünya, Güneş etrafında saat yönünün tersinde dolanmaktadır.",
"Ay kendi ekseni etrafında saat yönünün tersinde dönmektedir. Ay, Dünya ve Güneş etrafında saat yönünün tersinde dolanmaktadır.",
"Güneş, Dünya ve Ay modeli yaparken oyun hamuru, tel, pimpon topu, kağıt, karton, plastik tabak gibi değişik malzemeler kullanabilirsiniz. Modelde en büyük olan Güneş'i orta büyüklükte Dünya'yı, en küçük de Ay'ı temsil etmelidir.",
"Güneş'in yapısı gazlardan oluşmuştur. Güneş'in çok büyük bir kısmı hidrojen gazından oluşmaktadır. % 71 Hidrojen, % 26,5 Helyum, % 2,5 diğer gazlar bulunur."
"Güneş'inde Dünya gibi katmanları vardır. Güneş'in katmanları iç katmanlar ve Güneş Atmosferi olarak ikiye ayırabiliriz.",
"Güneş gazlardan meydana gelmiştir. Güneş, Güneş sisteminin merkezinde yer almaktadır. Güneş sistemindeki en büyük gök cismidir. Güneş büyük bir gök cismi olduğu için, çekim kuvveti diğer gezegenlerden daha fazladır. Güneş'in şekli küredir. Şekli top gibi yuvarlaktır. Güneş ısı ve ışık kaynağımızdır. Samanyolu galaksisi içerisinde bulunan 200.000 yıldızdan bir tanesidir. Güneş, Samanyolu galaksisinin etrafında dolanır. Güneş orta büyüklükte bir yıldızdır. Dünya'ya olan uzaklığı yaklaşık 150 milyon kilometredir. Güneş yaklaşık 5 milyar yaşındadır. Güneş'in oluşumu gaz ve toz bulutlarından meydana gelmiştir. Güneş beyaz renkte ışık yaymaktadır. Güneş'ten yayılan ışığın çok az bir miktarı Dünya'ya ulaşır. Güneş kendi ekseni etrafında dönme ve Samanyolu galaksisi içerisinde dolanma hareketi yapmaktadır. Kendi ekseni etrafında 25 günde döner. Güneş kendi ekseni etrafında batıdan doğuya doğru döner. (Saat yönünün tersi, sağdan sola doğru) Güneş'in çapı Dünya'nın 109 katıdır. Güneş'in sıcaklığı yüzeyinde 6.000°C, çekirdeğinde ise 15 milyon °C'dir. (Yaklaşık değerler) Güneş'te diğer yıldızlar gibi doğar, büyür ve enerjisi biterek ölecektir. Güneş yüzeyinde kısmen soğuk olan kısımlar bulunur. Koyu renkte görülen bu bölgelere Güneş Lekeleri denir. Kendi yaptığı teleskopla Güneş lekelerini ilk gözlemleyen kişi Galileo Galilei'dir. Galileo Galilei Güneş lekelerinin hareket ettiğini gözlemleyerek Güneş'in kendi ekseni etrafında döndüğünü bulmuştur. Güneş'te meydana gelen patlamalar sayesinde etrafa çok fazla enerji yayılır.",
"Dünya'nın her yeri karanlık olurdu. Güneş ışığı Dünya'ya ulaşmadığı için sürekli gece yaşanırdı. Aşırı soğuk yaşanırdı. Güneş, Dünya'yı ısıtan ana kaynaktır. Güneş ışınları olmadan Dünya hızla soğurdu. Bitkiler fotosentez yapamazdı. Güneş ışığı olmadan bitkiler fotosentez yapamaz. Fotosentez olmadan besin üretilemezdi. Okyanuslar donardı. Okyanuslar yüzeyden başlayarak donar, deniz yaşayan canlılar yok olurdu. Dünya'da yaşam son bulurdu. Bitkilerin ölmesiyle birlikte oksijen üretimi durur ve tüm canlılar oksijensiz kalarak ölür.",
"Güneş'e çıplak gözle bakmak göz sağlığı açısından zararlıdır. Ayrıca dürbün, teleskop, mercek ve kamera gibi araçlarla da bakılmamalıdır. Güneş gözlemi filtreli teleskopla yapılmalıdır. Güneş lekelerinin gözlemi dürbün kullanılarak yapılabilir. Dürbün Güneş'e doğru tutulur, beyaz kâğıt üzerinde Güneş'in görüntüsü oluşur. Kâğıt üzerinde oluşan koyu bölgeler Güneş lekeleridir. Dürbünün Güneş'e uygun bir pozisyonda olması gerekmektedir.",
"Güneş Dünya'dan çok uzakta olduğu için Ay ve Güneş aynı büyüklükte görünür. Güneş, Dünya ve Ay'dan büyüktür. Güneş içerisine yaklaşık 1 milyon 300 bin Dünya sığabilir. Güneş'in çapı Dünya'nın 109 katıdır. Dünya'nın çapı Ay'ın çapının 4 katıdır, Dünya, Güneş ve Ay modeli oluşturulduğunda Yaklaşık olarak Ayın yarıçapı 1 cm olacak şekilde model oluşturduğumuzda Dünya 4 cm , Güneş ise yaklaşık 400 cm büyüklüğünde yapılmalıdır. Güneş futbol topu büyüklüğünde çizersek, Dünya'yı yarım pirinç tanesi büyüklüğünde çizmeliyiz.",
"Güneş Dünya'dan çok uzakta olduğu için Ay ve Güneş aynı büyüklükte görünür. Güneş, Dünya ve Ay'dan büyüktür. Güneş içerisine yaklaşık 1 milyon 300 bin Dünya sığabilir. Güneş'in çapı Dünya'nın 109 katıdır. Dünya'nın çapı Ay'ın çapının 4 katıdır, Dünya, Güneş ve Ay modeli oluşturulduğunda Yaklaşık olarak Ayın yarıçapı 1 cm olacak şekilde model oluşturduğumuzda Dünya 4 cm , Güneş ise yaklaşık 400 cm büyüklüğünde yapılmalıdır. Güneş futbol topu büyüklüğünde çizersek, Dünya'yı yarım pirinç tanesi büyüklüğünde çizmeliyiz.",
"Güneş'in de Dünya gibi katmanları ve atmosferi vardır. Güneş'in katmanları merkezinden dışarıya doğru çekirdek, ışık küre, renk küre ve taç küredir. Işık küre, renk küre ve taç küre Güneş'in atmosferini oluşturur.",
"Ay, Dünya gibi hareket halindedir. Ay'ın üç çeşit hareketi vardır. Ay'ın hareketleri, kendi ekseni etrafında dönme, Dünya etrafında ve Güneş etrafında dolanma hareketleridir. Ay kendi ekseni etrafında dönme ve Dünya etrafındaki dolanma hareketini 27 gün 8 saatte tamamlar. Ay'ın evreleri 29 gün 12 saatte tamamlanır, bu süreye 1 ay denir. Ay, Dünya etrafında bir kez döndüğünde, kendi ekseni etrafında da bir kez dolanır. Dünya'dan Ay'a bakıldığında Ay'ın hep aynı tarafı görülür. Kendi ekseni etrafında ve Dünya etrafında dönme süresi eşit olduğu için aynı yüzü görünmektedir. Ay'ın Dünya'dan görülmeyen tarafına Ay'ın karanlık yüzü denir. Ay'ın Güneş etrafındaki hareketi Dünya ile eş zamanlı olarak 365 gün 6 saattir. Ay, Dünya ve kendi ekseni etrafında batıdan doğuya doğru (Saat yönünün tersi veya sağdan sola) döner.",
"Gece gökyüzüne baktığımızda Ay'ın farklı şekillerde görmekteyiz. Bunun nedeni Ay ışık kaynağı olmadığı içindir. Eğer ışık kaynağı olsaydı Güneş gibi hep aynı şekli görecektik. Ay Güneş'ten aldığı ışığı yansıtmaktadır. Ay, Dünya etrafındaki konumuna göre farklı şekillerde görülmektedir.",
"Ay ışık kaynağı değildir. Ay, Güneş'ten aldığı ışığı yansıtmaktadır. Ay her gece farklı şekillerde görünür. Buna ayın evreleri denir. Ay'ın 4 ana, 4 ara evresi olmak üzere 8 evresi bulunur. Ay'ın ana evreleri arasındaki süre yaklaşık bir hafta sürer.",
"1. Yeni Ay; Ay, Güneş ile Dünya arasında olduğu evredir. Ay'ın karanlık bölgesi Dünya'ya dönük olduğu için Ay gökyüzünde görülmez. 2. Hilal; Yeni ay evresiyle ilk dördün evresi arasında görülür. Dünya'dan bakıldığında Ay 'Ters C' harfine benzer. 3. İlk Dördün; Ay'ın sağ tarafının aydınlık olduğu evredir. Ay'ın şekli 'Düz D' harfine benzer. 4. Şişkin Ay; Ay, ilk dördün evresi ile dolunay evresi arasında görülen ara evredir. 5. Dolunay; Dünya, Güneş ve Ay'ın arasındadır. Ay'ın parlak tarafı Dünya'ya bakmaktadır. Ay'ın en parlak ve tam bir daire şeklinde görüldüğü evredir. 6. Şişkin Ay; Şişkin ay, dolunay evresi ile son dördün evresi arasında görülen ara evredir. 7; Son Dördün: Ay'ın sol tarafı aydınlık olduğu evredir. Ay'ın şekli 'Ters D' harfine benzer. 8. Hilal; Son dördün evresiyle yeni ay evresi arasında görülür. Dünya'dan bakıldığında Ay 'Düz C' harfine benzer.",
"Kütle madde miktarıdır. Ağırlık maddeye etki eden yer çekimi kuvvetidir. Kütle eşit kollu terazi ile ölçülür. Ağırlık dinamometre ile ölçülür. Kütle her yerde aynıdır, değişmez. Ağırlık bulunan yere göre değişir. Kütlenin birimi 'kilogram (kg)' dir. Ağırlığın 'newton (N)' dur. Kütle 'm' simgesi ile gösterilir, ağırlık 'G' simgesi ile gösterilir. Bir maddenin kütlesi uzayda sıfır olmaz, ancak ağırlığı sıfır olur.",
"Uzayda yer çekimi olmadığı için ağırlıkta sıfırdır. Ay'da ağırlık Dünya'daki ağırlığın altıda biridir. Burada 60 N ağırlığındaki cisim Ay'da 10 N'dur. Ağırlığın (Yer çekimi kuvvetinin) yönü Dünya'nın merkezine doğrudur. Ağırlık, cismin kütlesine ve cisme etki eden çekim kuvvetine bağlıdır. Ağırlık temas gerektirmeyen bir kuvvettir. Kütle ile ağırlık doğru orantılıdır. Kütle arttıkça ağırlıkta artar. Ağırlık deniz seviyesinden yukarı doğru çıktıkça azalır. Ağırlık ekvatordan kutuplara doğru gidildikçe artar.",
"Dünya dışındaki gök cisimlerinin uyguladıkları bu çekim kuvvetine kütle çekim kuvveti denir. Büyük bir gezegeninin kütle çekim kuvveti de fazladır. Bu nedenle Dünya'dan büyük gezegenlerde cisimlerin ağırlığı Dünya'dan fazladır. Ay, Dünya'dan küçük olduğu için kütle çekimi azdır. Bu nedenle Ay'da cisimlerin ağırlıkları azalır.",
"Hareketli cisimlerle temas ettiği yüzey arasında gerçekleşen, cismin hareketini zorlaştıran etkiye 'sürtünme kuvveti' denir. Topa vurduğumuzda topun bir süre sonra durması, bisikleti zorlanarak sürmemiz sürtünme kuvvetinden kaynaklanır.",
"Sürtünme kuvveti hareket yönüne zıttır. Sürtünme kuvveti temas gerektiren bir kuvvettir. Hareket eden cisimleri yavaşlatır ve durdurur. Duran cisimlerin hareket etmesini zorlaştırır. Cisimleri hareket ettirebilmek için sürtünme kuvvetini yenmek gerekir. Sürtünme kuvveti pürüzlü yüzeylerde daha fazla, kaygan yüzeylerde azdır. Sürtünme kuvveti yüzeyin cinsine bağlı olarak değişir. Sürtünme kuvveti cisimleri hareket ettirmez. Tamamen pürüzsüz bir yüzey yoktur.",
"Pürüzlü yüzeylerde sürtünme kuvveti fazladır. Zımpara kağıdı, halı, toprak, çakıl, çim saha gibi yüzeyler pürüzlü yüzeylerdir. Kaygan yüzeylerde sürtünme kuvveti azdır. Cam, buz, porselen, cilalı tahta, mermer kaygan yüzeylere örnek verilebilir.",
"Sürtünme kuvvetini azaltmak için yüzeyler pürüzsüz hale getirilir. Cisimlerin altına tekerlek takılması sürtünme kuvvetini azaltır. Makinelerin yağlanması sürtünme kuvvetini azaltır. Su sürtünme kuvvetini azaltır. Islak zeminlerde kayarak düşebiliriz. Kar ve buz sürtünme kuvvetini azaltır. Kışın arabaların tekerlerinin kaymasını engellemek için kış lastikleri ve zincir kullanılır.",
"Sürtünme kuvvetinin olumlu ve olumsuz etkileri vardır. Sürtünme kuvveti elbiselerimizi, ayakkabılarımızı aşındırır. Yazı yazabilmemiz, ayakta düşmeden durabilmemiz sürtünme kuvveti ile olur. Makine parçalarının aşınmasını engellemek içinde yağlanması sürtünmeyi azaltmak için yapılır. Buzdolabının tekerlekli olması sürtünme kuvvetini azaltır. Araçlara takılan kışlık lastiklerin sürtünmeyi artırıcı, yazıık lastiklerin sürtünmeyi azaltıcı desenleri vardır. Kibritin, çakmağın yanması sürtünme sonucu oluşan kıvılcımla gerçekleşir.",
"Havadaki sürtünme kuvvetine hava direnci denir. Hava direnci cisimlerin havadaki hızını azaltır. Havadaki cisim ne kadar büyükse sürtünme kuvveti o kadar fazla olur. Havada direncini azaltmak için özel tasarım araçlar yapılır.",
"Sudaki sürtünme kuvvetine su direnci denir. Su direnci, su içerisinde hareket eden cisimlerin hareketini zorlaştırır.",
"Balıkların pullu olması, gemilerin önünün 'V' şeklinde yapılması, yüzücülerin özel üretilmiş mayo ve bone kullanması, balıkların kaygan sıviyla kaplı olması, yüzücülerin suya atlarken ellerini birleştirmeleri, balıkların oval yapılarının olması su direncini azaltır.",
"Duran bir cismi hareket ettiren, hareket eden cismi durduran, cismin hızını yönünü ve şeklini değiştirebilen etkiye 'kuvvet' denir. Kuvvet kısaca itme ve çekmedir.",
"Kuvvet cismi hareket ettirebilir. Otomobile kuvvet uygulanarak hareket ettirilebilir. Hareket eden cisimler sürtünme kuvveti ile durabilir. Hareket eden cismin yönünü değiştirebilir. Ayağımızla bize gelen topun yönünü değiştirebiliriz. Cismin dönmesini sağlayabilir. Kuvvet uygulayarak kapıyı açabiliriz. Cismin şeklini değiştirebilir. Elimize aldığımız kağıdı buruşturabiliriz.",
"Arabanın itilmesi, dişçinin dişi çekmesi, çantanın kaldırılması, futbol oyuncusunun topa vurması, heykeltıraşın taşı yontması, kağıdı kesilmesi, yazı yazılması, baklava ustasının hamuru açması, kapı kolunu çevirerek kapının açılması, mıknatısın toplu iğneleri çekmesi, geminin suda yüzmesi, dalda duran elmanın yere düşmesi kuvvetle gerçekleşir.",
"Kuvvetin büyüklüğünü dinamometreyle ölçeriz. Kuvvet birimi Newton'dur, N harfi ile gösterilir. Dinamometre içerisinde esnek yay bulunur. Kuvvetin etkisi ile yay uzar ve üzerindeki değerler okunur. Yayın uzaması ile kuvvet doğru orantılıdır. Dinamometrenin ölçebileceği en fazla kuvvet yayın kalınlığına, cinsine ve boyuna bağlıdır. Dinamometrede kullanılan yay fazla esnek ise küçük kuvvetleri ölçebiliriz. Fazla kuvvet ölçebilen dinamometrelerin içinde kalın yay bulunur. Kalın yayın esneklik özelliği azdır. Her dinamometrenin ölçebileceği bir kuvvet sınırı vardır, bu sınır geçildiğinde içerisindeki yayın esneklik özelliği kaybolur, dinamometre bozulur.",
"Kuvvet etki ettiğinde şekil değiştiren, kuvvet ortadan kalktığında tekrar eski haline dönebilen cisimlere esnek cisim denir. Yay, lastik, sünger, balon, çorap, kauçuk esnek cisimdir. Hamur, sakız, kağıt esnek değildir.",
"Gerekli malzemeler;Pet şişe 1 adet, paket lastiği 1 adet, ataş 1 adet, fon kartonu, metre, makas, delgeç.Bu malzemeler ile dinamometre yapabilirsin bu konuda internetten videolar izlemeni öneririm.",
"Destek ve hareket sistemi iskelet ve kaslardan oluşur. İskeletimiz de kemik, eklem ve kıkırdaktan meydana gelir.",
"İskelet;- Kemik,- Eklem,- Kıkırdak, Kas: - Çizgili Kas, - Düz Kas, - Kalp Kası",
"Kemikler sert ve canlı yapılardır. kıkırdağın sertleşmesi sonucu kemikler oluşur. Anne karnındayken kıkırdak doku kalsiyum birikmesi sonucu kemiğe dönüşür. Kemikleşme yirmili yaşlara kadar devam eder.",
"Vücudumuzun dik durmasını sağlar.Kasların ve diğer organların tutunma yüzeyini oluşturur.Kan yapımında görevlidir.Vücuda şekil verir.Vücudumuz için gerekli kalsiyum, magnezyum ve fosfor gibi mineraller kemiklerde depolanır.İç organları dış etkilere karşı korur. (Kafatası beyini, göğüs kafesi kalp ve akciğeri korur.)Kemikler kaslarla beraber hareket etmemizi sağlar.",
"Kemikler yapısı ve şekline göre üçe ayrılır.1. Uzun kemik; Boyu eninden fazla olan kemiklerdir. İçlerinde sarı kemik iliği bulunur. Kol, bacak ve parmak kemikleri (Uyluk, kaval, baldır, dirsek, ön kol, pazı) uzun kemiktir.2. Kısa kemik; Eni boyuna yakın olan kemiklerdir. El ve ayak bilek kemikleri, omurlar kısa kemiktir.3. Yassı kemik; Yassı şekildeki kemiklerdir. Yapısında sarı kemik iliği bulunmaz. Kafatası, kaburga, leğen, kürek kemikleri yassı kemiklerdir.",
"İnsan vücudunda en uzun kemik uyluk kemiği, en kısa kemikte kulakta bulunan üzengi kemiğidir.",
"Kemikleri ve bazı organları görüntülemede röntgen kullanılır. Röntgen filmi incelenerek kemik kırıkları görülebilir.",
"Eklemler hareket yeteneklerine göre üçe ayrılır.1. Oynar eklem; Hareket yeteneği fazladır. Kemikler arasında boşluk ve eklem sıvısı vardır. Eklem sıvısı ve kıkırdak kemiklerin aşınmasını önler. Kol, bacak, parmak, bilek, omuzda bulunur.2. Yarı oynar eklem; Hareket yeteneği çok azdır. Kemikler arasında kıkırdak bulunur, eklem sıvısı bulunmaz. Yarı oynar eklem, Göğüs kafesi, boyun, omurga ve alt çenede bulunur.3. Oynamaz eklem; Hareketsiz eklemlerdir. Oynamaz eklem içerisinde eklem sıvısı yoktur. Testere dişleri gibi birbirine bağlanmışlardır. Kafatası, yüz, kalça ve kuyruk sokumunda oynamaz eklem bulunur.",
"Kıkırdak esnek bir yapıya sahiptir.Kemik uçlarındaki kıkırdak kemiğin boyuna uzamasını sağlar Kaygan bir yapıya sahip olduğu için kemiklerin birbirine sürtünerek aşınmasını önler.Kıkırdak iskelete esnek bir yapı oluşturarak kırılmasını önler.Kıkırdak uzun kemiklerde, kaburga uçlarında, burun, kulak kepçesi ve soluk borusunda bulur.Kaburga uçlarında bulunan kıkırdak, soluk alıp vermede esneklik kazandırır.",
"Kaslar kasılma ve gevşeme yeteneğine sahiptir.Kemiklerin ve iç organların çalışmasını sağlar.Kaslar yapı ve çalışmasına göre üç çeşittir.1. Çizgili kas; Kırmızı renklidir. Kemiklere tendonla bağlıdır. İsteğimizle çalışır. Hızlı çalışır, çabuk yorulur. Çiftler şeklinde bulunur. Birbirine zıt olarak çalışır. Kaslardan biri kasılırken diğeri gevşer.2. Düz kas; İç organlarımızda bulunur. İsteğimiz dışında çalışır. Beyaz renklidir. Yorulmaz, sürekli, yavaş ve ritmik çalışır. Mide, bağırsaklar, soluk borusu, yemek borusu, idrar kesesi, damarlarda düz kas bulunur.3. Kalp kası; Yapısı çizgili kasa, çalışması düz kasa benzer. Kırmızı renklidir. Hızlı ve ritmik çalışır. Yorulmaz. İsteğimiz dışında çalışır. Kaslar çiftler halindedir.",
"Gözle görülemeyen yapıları mercekler yardımıyla büyüterek görülmesini sağlayan araçlara mikroskop denir. Hücre çıplak gözle görülemez. Hücrenin görülmesi mikroskobun icadıyla mümkün olmuştur. Mikroskop üzerindeki mercekler sayesinde görüntü 10, 20, 40, 100 kat gibi değerlerde büyütebilir.",
"1. Mikroskop ışık kaynağı açılır.2. İncelenecek preparat hazırlanır.3. Preparat mikroskobun tablasına yerleştirilir.4. X ve Y ekseni ayar vidası ile preparat objektif altına getirilir.5. Kaba ve ince ayar vidası kullanılarak net görüntü elde edilir.6. Detaylı görüntü elde etmek için objektif değiştirilebilir.",
"Zacharias Janssen (Zakaryas Yansen) ilk mikroskobu buldu.Hücreyi ilk keşfeden kişi Robert Hooke(Rabırt Huk)tur.Şişe mantarını incelerken küçük odaların olduğunu gördü.Buna içi boş oda anlamına gelen Hücre adını verdi.Anton Van Leeuwenhock (Lövenhuk) mikroskopla havuz suyunu incelerken hareket eden küçük canlıları gördü.",
"Canlıların canllık özelliğini gösteren en küçük yapıtaşına hücre denir. Canlıların vücudu hücrelerden oluştur. Hücreler canlıdır. Kendi başına yaşayabilme özelliği gösterir.",
"Hücre üç temel kısımdan meydana gelir. Bunlar diştan içe doğru hücre zarı, sitoplazma ve çekirdektir.",
"Hücreyi diş etkilere karşı korur.Esnek bir yapısı vardır, üzerinde geçitler (Por) bulunur.Porlar aracılığı ile madde alışverişi yapar, seçici geçirgendir.Her maddeyi içeri almaz veya dışarı çıkarmaz.Her maddeyi içeri almaz veya dışarı çıkarmaz.Hücreye şekil verir.Hücreyi diş etkilerden korur.Hücrenin madde alışverişini kontrol eder.Hücrenin dağılmasını engeller.Canlıdır.",
"Hücre zarının etrafını saran sert ve dayanıklı bir yapıdır.Bitki hücrelerinde bulunur.Bakteri ve mantarlarda da bulunmaktadır.Hayvan hücrelerinde bulunmaz.Hücre zarının etrafını sarar.Bitkiye dayanıklılık sağlar.Bitkiyi iç ve dış etkilere karşı korur.Hücre duvarı tam geçirgendir.Cansızdır."
"Hücre zarı ile çekirdek arasını doldurur, yumurta akı kıvamındadır.Yarı saydam ve akışkandır.Yapısının çok büyük bir kısmı sudur.Yaşamsal olaylar sitoplazmada gerçekleşir.Solunum, boşaltım, sindirim, madde sentezi (üretimi), enerji üretimi, beslenme olayları gerçekleştirilir.Yaşamsal olayların gerçekleştiği yapılara organel adı verilir.",
"1. Endoplazmik Retikulum; Hücrenin içini ağ gibi saran kanal sistemidir. Hücre içine maddelerin taşınmasını sağlar. Bir ülkedeki karayollarına benzer.2. Golgi Cisimciği; Salgı maddelerinin üretilmesini, kesecikler halinde paketlenmesi sağlar. Salgı üreten hücrelerde normalden fazla bulunur. Tükürük bezi, ter bezi, süt bezi, deri golgi cisimciğinin fazla olduğu yerlerdir. Çiçekli bitkilerde bal özü salgılanmasını gerçekleştirir.3. Mitokondr; Besin ve oksijeni yakarak hücre için gerekli enerjiyi üretir. Hücrenin enerji santralleridir. Enerji tüketiminin fazla olduğu yerlerde mitokondri sayısı da fazladır. Sinir, kas, karaciğer hücrelerinde fazlaca bulunur.4. Lizozom; Hücre içindeki maddelerin sindirilmesini sağlar. Büyük yapılı besinleri küçük parçalara ayırır. Yaşlanmış dokuları, mikropları yok eder. Hayvan hücrelerinde bulunur.5. Ribozom; Bütün hücrelerde bulunur. En küçük organeldir. Proteinlerin üretimini sağlar. Protein üretiminin fazla olduğu yerlerde ribozom sayısı fazladır. Genç hücrelerde, karaciğer ve salgı bezlerinde fazla bulunur.6. Sentrozom; Sentrozom çiftler halinde bulunur. Sentrozom iki sentriyolden oluşur. Hücre bölünmesinde görevlidir. Hayvan hücrelerinde bulunur.7. Koful; Hücrede depo görevini görür. Besin maddeleri, artık maddeler ya da atık maddeler bulunabilir. Hayvan hücresinde küçük, bitki hücresinde büyük yapılıdır.8. Kloroplast; Kloroplast yeşil renklidir. Fotosentez yaparak besin ve oksijen üretir. Yalnızca bitkinin yeşil olan yerlerinde bulunur.",
"Çekirdek hücrenin ortasında yer alan yönetici kısımdır. Hücrenin yaşamsal faaliyetleri buradan denetlenir ve yönetilir. Canlıya ait kalıtsal özellikler çekirdekte bulunur. Olgunlaşmış alyuvar hücrelerinde çekirdek bulunmaz. Çizgili kas hücrelerinde ise birden fazla çekirdek bulunur.",
"1. Bitki hücresinde kloroplast vardır, hayvan hücresinde yoktur.2. Bitki hücresinde hücre duvarı vardır, hayvan hücresinde yoktur.3. Hayvan hücresinde sentrozom vardır, bitki hücresinde yoktur.4. Bitki hücresinde koful büyük ve az sayıdadır, hayvan hücresinde küçük ve fazladır.5. Bitki hücresi köşelidir, hayvan hücresi yuvarlaktır.",
"Çok hücreli canlılarda hücreler bir arada bulunur. Aynı yapı ve görevde bulunan hücreler dokuyu oluşturur. Örneğin kas hücreleri kas dokusunu, kemik hücreleri kemik dokusunu oluşturur. Farklı dokular bir araya gelerek organları oluşturur. Örneğin kas dokusu ve diğer dokular bir araya gelerek kalp organını oluşturur. Belirli görevleri yerine getiren organlar bir araya gelerek sistemleri oluşturur. Örneğin kalp, kan ve damarlar bir araya gelerek dolaşım sistemini oluşturur. Farklı sistemler bir araya gelerek organizmayı oluşturur. Örneğin dolaşım sistemi, destek ve hareket sistemi, solunum sistemi gibi sistemler de organizmayı oluşturur. İnsan, trilyonlarca hücreden oluşan ve uyum içerisinde çalışan bir organizmadır.Hücreden organizmaya basitten karmaşığa doğru sıralanışı;Hücre → Doku → Organ → Sistem → Organizma",
"Işık bir madde ile karşılaşınca, maddeyi geçebilir, yansıyabilir, soğrulabilir.",
"Işığı geçirmeyen maddelere opak madde denir. Işık saydam olmayan (Opak) maddelerden geçemez. Opak maddenin arkasında gölge oluşur. Tahta, taş, duvar, sıra, alüminyum folyo, ayna opak maddelerdir.",
"Işığın bir kısmını geçiren, bir kısmını geçirmeyen maddelere yarı saydam madde denir. Yarı saydam maddelerin arkasındaki cisimler tam olarak görülemez. Yarı saydam maddenin arkasında yarı gölge oluşur. Yağlı kağıt, buzlu cam, ince tül perde, bazı plastikler, sisli hava yarı saydam maddelerdir.",
"Gelen ışığı geçiren maddeler saydam maddedir. Saydam maddelerin arkasındakileri gösterir. Saydam maddelerin gölgesi oluşmaz. Saydam maddelerin ışığın geçirme özelliği günlük yaşamda kullanılır. Pencerelerde cam kullanılması içerinin aydınlık olmasını sağlar. Saydam maddeler gözlük, saat, ampul yapımında kullanılır. Cam, su, alkol, elmas, hava, şeffaf poşet saydam maddelere örnektir.",
"Maddelerin saydamlık özelliği değişebilir. Örneğin hava saydam madde iken, sisli hava saydam değildir. Işık geçirme durumu cismin kalınlığına da bağlıdır. Karton opak bir maddedir fakat çok fazla inceleştirildiğinde yarı saydam özellik gösterir. Su saydamdır fakat çok derin okyanus tabanlarına ışık ulaşamaz. Bazı ışınlar çok kalın engelleri aşabilir. X-ışınları insan vücudu, tahta, valiz gibi engellerden geçebilir.",
"Işık opak maddelerden geçemez. Işığın ulaşamadığı cismin arkasındaki karanlık yere gölge denir. Güneş, el feneri ve lambalar gibi ışık kaynakları, etrafı aydınlatır. Opak maddeler ışığın geçişini engeller. Işık geçen bölgeler aydınlık olurken, ışığı geçirmeyen bölgeler karanlıkta kalır. Bu sayede cismin şekline benzeyen gölgesi oluşur. Cisimlerin şekli değiştikçe gölgesinin şeklide değişir. Işığı hiç almayan yerlerde tam gölge oluşur. Öğle vakti Güneş gölgemizi oluşturması tam gölgedir. Tam gölgenin oluşması ışığın doğrusal yayıldığını gösterir. Büyük cisimlerin büyük, küçük cisimlerin küçük gölgesi oluşur. Cismin şekli nasılsa, gölgesi de ona benzer.",
"Opak bir cismin gölgesinin çizilmesi için:1. Işık kaynağından çıkan ışınları, cismin uç noktalarını çizgi ile birleştirerek ekrana kadar uzatalım.2. Ekran üzerinde oluşan noktaları birleştirelim.3. Noktaların oluşturduğu alanı siyaha boyayalım.",
"Işık kaynağı ile cisim arasındaki mesafe azalırsa oluşan gölge büyür. Cisim ile perde arasındaki mesafe azalırsa oluşan gölge küçülür.",
"İki ışık kaynağı bulunan bir yerde, ışık kaynağının birinde alıp diğerinden almıyorsa yarı gölge oluşur. Bir futbol sahasında gece oynanan maçlarda oyuncuların birden fazla yarı gölgesi oluşur.",
"Gölge oyunu; Kültürel bir mirasımız olan gölge oyunu, pek çok kişi tarafından beğeni ile izlenmektedir.Ellerimiz ile değişik hayvan figürleri oluşturabiliriz. Işık kaynağına elimizi tutarak kuş, tavşan şekilleri oluşturabiliriz.Işık ve gölge oyunlarından yararlanarak pek çok sanatsal eserler oluşturulmaktadır.",
"Işık bir enerjidir. Bir ışık kaynağından ışık ışınları, her yöne doğrular boyunca ışık yayar. Işık doğrusal olarak yayılır. Işık, ışınlar çizilerek gösterilir. Işık ışınlarının önüne bir engel gelmediği sürece ilerlemesine devam eder. Işık hava, su, cam gibi saydam ortamlarda ve boşlukta yayılır. Işığın yayılabilmesi için maddesel ortama ihtiyacı yoktur.",
"1. Bulutların arasından gelen ışığın doğrusal olarak ilerlediğini görürüz.2. Sahnede spot ışıkları ışığın doğrusal olarak yayıldığını gösterir.3. Yanan bir muma düz bir boru ile bakıldığında görülür, eğri boru ile bakıldığında ışığın görülmez.4. Deniz fenerinden çıkan ışık ışınları etrafa doğrusal yayılır.5. Araçların farlarından çıkan ışığın sadece ön tarafı aydınlatır.6. El fenerinden çıkan ışık doğrusal yayılır.7. Futbol sahalarında kullanılan aydınlatma ışıkları doğrusal yayılır.8. Gölgenin oluşması ışığın doğrusal yayıldığını gösterir.9. Tam gölgenin oluşması sırasında cisim ile gölgesinin birbirine benzemesi ışığın doğrusal yayıldığını gösterir.10. Güneş ve Ay tutulması ışığın doğrusal yayıldığını gösterir.",
"Etrafa ışık saçan maddeler ışık kaynağıdır. İşık kaynakları doğal ve yapay olmak üzere ikiye ayrılır.",
"1. Güneş (En büyük doğal ışık kaynağımızdır)2. Yıldızlar3. Yıldırım4. Şimşek5. Ateş böceği6. Fener balığı7. Lav8. Arora (Kuzey ışıkları)9. Yakamoz (Işık saçan planktonlar)10. Işık saçan denizanası",
"1. Mum2. El feneri3. Ampul4. Meşale5. Ateş6. Gaz lambası",
"Maddeyi oluşturan ve maddenin özelliğini gösteren en küçük kısma maddenin taneciği (atom) denir. Bütün maddeler tanecikli yapılıdır. Isı, ışık, ses ve elektrik madde değil, enerjidir. Madde tanecikli yapıdadır. Maddenin taneciklerden oluştuğunu nasıl anlarız: 1. Gaz maddelerin sıkıştırılabilmesi, 2. İyodun alkolde dağılması, 3. Şekerin ve tuzun suda çözünmesi, 4. Parfüm kokusunun oda içerisinde dağılması, 5. Boyanın suda dağılması. Madde içinde bulunan atomlar üç çeşit hareketleri vardır: titreşim, öteleme ve dönme hareketidir.",
"Maddeyi oluşturan tanecikler arasındaki boşluklar maddenin fiziksel halini belirler. Tanecikler arasındaki boşluklar katı halde en az, gaz halinde en fazladır. Madde katı, sıvı ve gaz olarak üç halde bulunur. 1. Katı hal; Maddenin en düzenli halidir. Taneciklerin arasındaki boşluk çok azdır. Sıkıştırılamaz. Akışkan değildir. Belirli bir şekli ve hacmi vardır. Tanecikler titreşim hareketi yapar, öteleme ve dönme hareketi yapmaz. 2. Sıvı hal; Tanecikleri arasındaki boşluk katılara göre daha fazladır. Sıkıştırılamaz olarak kabul edilir. Akışkandır. Belirli bir hacmi vardır. Bulundukları kabın şeklini alır. Tanecikleri titreşim, dönme ve öteleme hareketi yapar. 3. Gaz hal; Maddenin en düzensiz halidir. Tanecikler bağımsız hareket eder. Tanecikleri arasında çok fazla boşluk vardır. Sıkıştırılabilir. Sıkıştırıldıkça (basınç arttıkça) taneciklerin arasındaki boşluk azalır. Büyük bir kapta (basınç azaldıkça) taneciklerin arasındaki boşluk artar. Akışkandır. Belirli bir şekli ve hacmi yoktur. Bulundukları kabın her tarafını doldurur. Tanecikleri titreşim, dönme ve öteleme hareketi yapar.",
"Isı; Sıcaklığı yüksek olan maddeden sıcaklığı düşük olan maddeye aktarılan enerjiye isı denir. Isı bir enerjidir. Bir maddenin ısısı doğrudan ölçülemez. Bir maddenin verdiği veya aldığı ısı kalorimetre kabı ile ölçülebilir. Isı birimi kalori (cal) ve Joule (J) dir. Sıcaklık;Bir maddenin ısısının ortalamasına sıcaklık denir. Sıcaklık bir maddenin aldığı veya verdiği ısının göstergesidir. Isı alan madde ısınır ve sıcaklığı artar. Isı veren madde soğur ve sıcaklığı azalır. Sıcaklık birimi santigrat derecedir (°C).",
"1. Isı bir enerjidir. Sıcaklık enerji değildir, ısının göstergesidir. 2. Isı kalorimetre kabı ile ölçülür. Sıcaklık termometre ile ölçülür. 3. Bir maddenin ısısı doğrudan ölçülemez, sıcaklık doğrudan ölçülebilir. 4. Isının birimi joule (J) ve kalori (cal) dir. Sıcaklığın birimi santigrat derecedir (°C). 5. Isı maddeler arasında alınıp verilebilir. Sıcaklığın alışverişi olmaz. 6. Isı alan her maddenin sıcaklığı artmaz.(Hal değişiminde) Sıcaklığı artan madde isı alıyor demektir.",
"Maddelerin katı, sıvı ve gaz olmak üzere üç hali vardır. Madde bir halden başka hale değişmesine hal değişimi denir. Buzun erimesi, suyun buharlaşması, demirin erimesi birer hal değişimidir. A-Erime;Katı maddelerin ısı alarak sıvı hale geçmesine erime denir. Erime sırasında sabit kalan sıcaklığa erime sıcaklığı (erime noktası) denir. B- Donma; Saf bir maddenin sıvı halden katı hale geçmesine donma denir. Donma olayının gerçekleştiği sıcaklığa donma sıcaklığı (donma noktası) denir. C- Buharlaşma; Sıvıların ısı alarak gaz hale geçmesine buharlaşma denir. D- Yoğuşma; Gaz haldeki maddenin sıvı hale geçmesine yoğuşma denir. E- Süblimleşme; Katı haldeki maddenin ısı alarak gaz haline geçmesine süblimleşme denir. F- Kırağılaşma; Gaz bir maddenin ısı vererek doğrudan katılaşmasına kırağılaşma denir.",
"1. Aile ve ülke ekonomisine katkı sağlar. 2. Doğal kaynakların tükenme hızını azaltır. 3. İnsan sağlığını korur. 4. Evimiz yazın serin, kışın ise sıcak olur. 5. Fosil yakıt kullanımı azalmasından dolayı çevre kirliliği azalır. 6. Hava kirliliğine bağlı hastalıklar azalacaktır. 7. Bina içerisinde terleme, küflenme, boya kabarmaları olmayacaktır. 8. Binanın ömrünü uzatır.",
"Isı iletkenleri; Bakır, Altın, Demir, Alüminyum, Kurşun, Çinko, Çelik, Gümüş, Metal para, Platin, Civa, Titanyum, Sodyum, Magnezyum, Kalsiyum, Kalay, Nikel, Kobalt, Krom, Berilyum, Bronz, Lehim, Elmas. Isı yalıtkanları; Tahta (Ahşap), Hava, Plastik, Kumaş, Saman, Cam yünü, Plastik köpük, Bakalit, Kağıt, Pamuk, Yün, Deri, Elyaf, Cam, Beton, Su, Katran, Silikon yünü, Kiremit, Gaz beton, Yağ, Porselen, Tuğla.",
"1. Ekonomik olmalıdır. 2. Yanmaya karşı dayanıklı olmalıdır. 3. Zamanla beraber yapısında bozulma olmamalıdır. 4. Mikroorganizma ve böcekler çoğalmamalıdır. 5. İnsan sağlığına ve doğaya zarar vermemelidir. 6. Çevre şartlarından olumsuz etkilenmemelidir. 7. Kullanımı kolay olmalıdır.",
"1. Taş Yünü: Yanmaz, iç ve dış duvarlarda kullanılır, uzun ömürlüdür. 2. Strafor köpük: Kolay yanar, iç ve dış duvarda kullanılır, uzun ömürlüdür. 3. Cam Yünü: Zor yanar, sıcak su borularında iç ve dış kaplamalarda kullanılır, uzun ömürlüdür. 4. Silikon Yünü: Zor yanar, dış duvarda kullanılır, uzun ömürlüdür. 5. Ahşap: Kolay yanar, iç duvarlarda kullanılır, kısa ömürlüdür. 6. Seramik Yünü: Yanmaz, dış duvar, çatı ve döşemelerde kullanılır, uzun ömürlüdür. 7. XPS (Yoğun Strafor Köpük): Zor yanar, dış duvar, çatı ve döşemelerde kullanılır, uzun ömürlüdür.",
"Pil, ampul, anahtar, bağlantı kablosu ve duydan oluşan elektrik devresine basit bir elektrik devresi denir. Basit elektrik devresinde birden fazla pil ve ampul kullanılabilir.",
"Pil; Elektrik enerjisi üretir. Pilin içerisinde kimyasal enerji elektrik enerjisine dönüşür. Pilin + ve - kutupları vardır. Ampul; Elektrik enerjisini ışık enerjisine çevirir. Ampulün + ve - kutupları yoktur. Bağlantı kablosu; Elektrik enerjisini taşır. Devre elemanları birbirine bağlantı kablosu ile bağlanır. Anahtar; Devrenin açılıp kapanmasını sağlar. Anahtar açık durumda iken elektrik iletilmez, kapalı durumda iletilir. Duy: Ampulün takıldığı yerdir. Basit elektrik devresinde duy olmadan da ampul ışık verebilir. Pil Yatağı; Pillerin bağlantısının yapılmasını sağlar. Basit elektrik devresinde pil yatağı olmadan da ampul ışık verebilir.",
"1. Pil bitmiş olabilir. 2. Bağlantı kablosu kopuk olabilir. 3. Anahtar açık olabilir. 4. Ampul patlamış olabilir. 5. Ampul duya tam yerleşmemiş olabilir. 6. Piller ters bağlanmış olabilir. 7. Elektrik devresinde, kısa devre olabilir. 8. Devreye çok fazla ampul bağlanmış olabilir. (Pilin gücü hepsini çalıştırmaya yetmez.) 9. Bağlantı yerleri paslanmış olabilir. (Pas elektrik akımının geçişini azaltır.)",
"Bilimsel araştırma yapılırken, karşılaşılan problemlerin çözümü için bazı yöntemler geliştirilmiştir. Bilimsel bir araştırmada problemin çözümü için kontrollü deney yapılır.",
"Bir deneyde bilerek yapılan değişikliklere değişken denir. Üç tür değişken vardır; Bağımsız değişken, Bağımlı değişken, Kontrol edilen değişken (Sabit tutulan değişken).",
"Bağımsız değişken; Pil sayısı. Bağımlı değişken; Ampulün parlaklığı. Kontrol edilen değişken; Anahtar, kablo, duy, ampul. Sonuç; Devrede pil sayısı artırılırsa ampul parlaklığı artar.",
"Bağımsız değişken; Ampul sayısı. Bağımlı değişken; Ampulün parlaklığı. Kontrol edilen değişken; Pil sayısı, anahtar, kablo. Sonuç; Devrede ampul sayısı artarsa parlaklık azalır.",
"Evimizde bilgisayar, televizyon, ampul gibi elektrikli araçları çalıştırmak için elektrik düğmeleri yapılmıştır. Elektrik düğmeleri, açma kapama görevi yapmaktadır. Ampulün ışık vermesi için lambayı aç deriz, fakat lamba çalışırken anahtarı kapatırız. Anahtar açık durumda iken ampul çalışmaz.",
"1. Devre elemanları sembollerinin gösterilmesi ortak bilimsel dilin oluşmasını sağlar. Dünyanın her yerinde devre elemanları aynı sembolle gösterilmektedir. 2. Bir elektrikli araç nerede üretilirse üretilsin herkes bu devre elemanlarını ve devre şemalarını anlayabilir. 3. Devre elemanlarının resmini çizmek zor ve zaman alıcıdır.",
"Pil; Elektrik enerjisi üretir. Pilde kimyasal enerji elektrik enerjisine dönüşür. Pilin + ve - kutbu vardır. Piller seri bağlanarak batarya elde edilir. Ampul; Elektrik enerjisinden ışık üretir. Ampulün + ve - kutbu yoktur. Bağlantı Kablosu; Devre elemanlarını birbirine bağlar. Elektrik enerjisinin taşınmasını sağlar. Anahtar; Devreden geçen elektriği kontrol eder. Anahtar açık halde iken elektrik geçmez, kapalı halde geçer.",
"Duy; Devreye ampulü bağlamak için duy kullanılır. Duy basit elektrik devresinde sembolle gösterilmez. Pil Yatağı; Pillerin bağlanması için de pil yatağı kullanılır. Pil yatağının basit elektrik devresinde sembolle gösterilmez.",
"Devre elemanlarının sembolleri kullanılarak devre şeması oluşturulur. Bütün elektrikli cihazların devre şeması vardır. Bir elektrik devresi kurulmadan önce devre şeması çizilir. Bu şemaya bakarak elektrik devresi hakkında bilgi sahibi oluruz. Ayrıca devrenin çalışıp çalışmayacağını şemaya bakarak anlayabiliriz.",
"Atık; Kullanım süresi dolan ve yaşadığımız yerden uzaklaşması gereken her türlü maddeye atık denir. Çöp; Atıkların içerisinde hiçbir şekilde kullanılamayacak olan maddelere çöp denir. Kağıt, cam, plastik, karton, metaller çöp değildir.",
"Yeniden kullanma; Atık maddelerin hiçbir işlem yapılmadan kullanılmasına yeniden kullanma denir. Geri dönüşüm; Atıkların bazı işlemlerden geçirilerek tekrar kullanılmasına geri dönüşüm denir.",
"Bitkisel ve hayvansal atıkların nemli ve oksijenli ortamda mikroorganizmalar tarafından bozunarak organik gübreye dönüşmesi sonucu kompost oluşur.",
"Atık ürünlerden enerji veya yeni ürün elde edilmesine geri kazanım denir. Organik atıklardan gübre yapımı, bitkisel ve hayvansal atıklardan biyogaz elde edilmesi, atık yağlardan yakıt elde edilmesi geri kazanıma örnek verilebilir.",
"Evde kullanımdan düşmüş veya çöp durumunda olan maddelere evsel atık denir. Evde kullanılan atık sular, atık yağlar, kağıt, poşet, pil, şişe, kutu, plastikler, boya atıkları, eski mobilyalar, eskimiş elbiseler, metaller, eskimiş elektronik araçlar, sebze ve meyve atıkları, yemek atıkları evsel atıktır.",
"Katı haldeki evsel atıklardır. Ambalaj atıkları, yiyecek atıkları, ev eşyası atıkları, kül evsel katı atıktır.",
"Sıvı haldeki evsel atıklardır. Kızartma yağı, atık sular evsel sıvı atıktır. Evsel sıvı atıklar arıtma tesislerinde arıtılabilir.",
"Bitki ve hayvan kaynaklı atıklara organik atık denir.",
"Sağlık kuruluşlarının çalışmalarında oluşan atıklar tıbbi atıktır. Yara bandı, enjektör, pamuk, sargı bezi, diyaliz atıkları, eldiven, ilaç kutuları tıbbi atıktır. Not; Tibbi atıklara kesinlikle temas edilmemelidir.",
"1. Ayırma; Plastik, kağıt, cam ürünler için ayrı ayrı toplama alanlarda ayrıştırılmalıdır. 2. Sınıflandırma; Ayrılan atıklar sınıflandırılmış olur. Sınıflanan malzemeler ayrı ayrı taşınmalıdır. 3. Değerlendirme; Değerlendirilebilen atıklar, fiziksel ve kimyasal işlemlerden geçirilerek yeni ürün oluşur.",
"Geri dönüştürülebilen evsel atıklar nelerdir?",
"1. Kağıt ürünleri; Kağıt, karton, gazete, dergi, kitap. 2. Metal ürünleri; Teneke kutu, alüminyum folyo, içecek kutuları, kablolar, eski mutfak araç gereçleri. 3. Plastik ürünleri; Pet şişe, poşet. 4. Cam ürünleri; Cam şişe, kavanoz. 5. Piller; Akümülatör (Akü), şarjlı piller, bataryalar. Ayrıca elektronik cihazlar, beton, atık yağlar, ahşap ve tekstil atıkları geri dönüştürülebilir.",
"1. Yağlı kağıt, ıslanmış kağıt, besin atığı bulaşmış kağıtlar. 2. Pencere camı, ayna, kristaller, borcam, telli cam. 3. Naylon, strafor köpük, oyuncak. 4. Ampul, floresan. 5. Bebek bezleri, ıslak mendil. 6. İçinde motor yağı, antifriz, benzin konulan şişeler. 7. Tek kullanımlık plastikten yapılan bardak, tabak, çatal, kaşık, pipet. 8. Seramik ürünler, porselen tabak.",
"1. Çevremizin temiz tutulması sağlanır. 2. Ekonomiye katkı sağlanır. 3. Doğal kaynaklar korunmuş olur. 4. Yeni iş imkanları oluşur. 5. Enerji tasarrufu sağlanır. 6. Atık miktarının azalmasına neden olur.",
"Atık yönetimi, atıkların toplanması, taşınması, değerlendirilmesi ve ortadan kaldırılması işlemlerini kapsar.",
"1. TAP; Atık pillerin toplanması, geri kazanımı veya ortadan kaldırılmasında görevli kuruluş. 2. ÇEVKO; Ambalaj atıklarının değerlendiren kuruluş. 3. AGED; Atık kağıt ve geri dönüşümcüler derneği. 4. PETDER; Atık yağların toplanması, geri kazanımı veya ortadan kaldırılmasında görevli kuruluş. 5. TURMEPA; Deniz kirliliğini önleme derneği. 6. PAGÇEV; Türk plastik sanayicileri araştırma geliştirme ve eğitim vakfı."
]

# Liste uzunluklarını kontrol etme
if len(sorular) != len(cevaplar):
    print("Uyarı: Sorular ve cevaplar listeleri eşit uzunlukta değil!")
    print(f"Soru sayısı: {len(sorular)}, Cevap sayısı: {len(cevaplar)}")
else:
    print("Sorular ve cevaplar listeleri eşit uzunluktadır.")

# data.txt dosyasına yazma
with open('data.txt', 'w', encoding='utf-8') as file:
    for soru, cevap in zip(sorular, cevaplar):
        file.write(f'"{soru}": {cevap}\n')  # Her soru ve cevabı yeni bir satıra yaz

print("Sorular ve cevaplar data.txt dosyasına yazıldı.")